import screeninfo

display_info = screeninfo.get_monitors()[0]
SCREEN_WIDTH = display_info.width
SCREEN_HEIGHT = display_info.height

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
SHOT_RADIUS = 5

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3

MEGA_BLAST_RADIUS = SHOT_RADIUS*10
MEGA_BLAST_SPEED = PLAYER_SHOT_SPEED*2
MEGA_BLAST_COOLDOWN = 0.3